### ISSUE TITLE
meet some problems when adding to a new unity project

### ISSUE THREAD

**Issue by hahastephanie** [levifussell/SimpleUnityClothSimulator#1]
I can run the code of SampleScene part successfully, but I fail when I try to add these files to a new unity project. I add CCloth.cs to Cloth, add SphereCollisionConstraint.cs to Sphere and add CapsuleCollisionConstraint.cs to two Capsule. After running, the error is "NullReferenceException: Object reference not set to an instance of an object at Assets/Scripts/TableCloth/ClothPhysics.cs:142". 
`c.ApplyConstraint(this.points);`

What else I need to do with points in function ApplyCollisionConstraints() to fix the problem? Thanks a lot for any answers : )

@levifussell

**Comment by hahastephanie** [comment]
I fix it successfully.

**Comment by levifussell** [comment]
@hahastephanie glad to hear you figured it out! Sorry for the late reply, only just saw this.

Let me know if you have further questions.
